name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: ruby/setup-ruby@master
      with:
        ruby-version: 3

    - name: Jekyll Build
      run: |
        bundle update --bundler
        bundle install
        bundle exec jekyll build

    - name: Remove extensions
      run: |
        find _site/ -type f ! -iname 'index.html' -iname '*.html' -print0 | while read -d $'\0' f; do mv "$f" "${f%.html}"; done

    - name: Publish to AWS S3
      uses: opspresso/action-s3-sync@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-2"
        FROM_PATH: "_site"
        DEST_PATH: "s3://kaufman.dev"
        OPTIONS: "--acl public-read"

    - uses: awact/cloudfront-action@master
      env:
        SOURCE_DIR: '/'
        AWS_REGION: 'us-east-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
